title: Aadi Bery
logo: docs/assets/headshot.JPG
description: Computer Science Undergraduate | Research Assistant | Tutor
contact:
  email: aadibery@gmail.com
  phone: (562) 266 6887
  linkedin: https://www.linkedin.com/in/aadi-bery/
#show_downloadeds: true
theme: jekyll-theme-minimal
